# -*- coding: utf-8 -*-
"""assigment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AtRX21daIG0LUyHaebPXQwFBAUyySpVE

Return the uncensored string in the case of a censored string and censored vowels
Example:
sansür("*r*b*m* p*rk *tt*m","aaaıaei") arabamı park ettim
"""

def sansür(sansürlü,sesli):
  n=0
  for i in sansürlü:
    if i =="*":
        sansürlü=sansürlü.replace("*",sesli[n])
        n+=1
        return sansürlü   
print(sansür("pyth*n", "o"))