# -*- coding: utf-8 -*-
"""assigment_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17rM-YRLUn9mpfkFk5nLtGV4jCpDLm0Yk

Şubat ayının 29 çektiği yıllar artık yıllardır. Girilen input değerinin artık yıl olup olmadığını bulalım
"""

while True:
  leap_year = input("Lütfen dört haneli bir yıl giriniz. ")
  try:
    ileap_year = int(leap_year)
  except:
    print("Geçersiz veri! Lütfen rakamlarla bir yıl giriniz.")
    continue
  if ileap_year % 4 ==0:
    if ileap_year %400==0:
      print(f"{ileap_year} artık yıldır.")
    elif ileap_year %100 ==0:
      print(f"{ileap_year} artık yıl değildir.")
    break